from .album import Album
from .car import Car
from .fruit import Fruit
from .manufacturer import Manufacturer
from .musician import Musician
from .person import Person
from .runner import Runner
from .shirt import Shirt
from .topping import Topping
